// src/components/Projects/index.svelte
<script lang="ts">
  import CategoryBlock from '$components/common/CategoryBlock.svelte';
  import CategoryTitle from '$components/common/CategoryTitle.svelte';
  import type { Project, ResumeData } from '$types/resumeData';
  import type { Writable } from 'svelte/store';
  import { getContext } from 'svelte';
  import ProjectSection from './ProjectSection.svelte';

  let projects: Project[];
  const resumeData = getContext<Writable<ResumeData>>('resumeData');
  resumeData.subscribe((value) => (projects = value.projects));
</script>

<CategoryBlock>
  <CategoryTitle title={'Projects'} />
  <div class="space-y-3">
    {#each projects as project}
      <ProjectSection {...project} />
    {/each}
  </div>
</CategoryBlock>

// src/components/Projects/index.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import { computed } from 'vue';
import { useResumeContentStore } from '@/stores/resumeContent';
import CategoryBlock from '@/components/common/CategoryBlock.vue';
import CategoryTitle from '@/components/common/CategoryTitle.vue';
import ProjectSection from './ProjectSection.vue';

const resumeContentStore = useResumeContentStore();
const { content } = storeToRefs(resumeContentStore);
const projects = computed(() => content.value.projects);
</script>

<template>
  <CategoryBlock>
    <CategoryTitle title="Projects" />
    <div class="space-y-3"></div>
    <ProjectSection
      v-for="project of projects"
      :key="project.title"
      :title="project.title"
      :brief-description="project.briefDescription"
      :start-date="project.startDate"
      :end-date="project.endDate"
      :project-url="project.projectUrl"
      :repo-url="project.repoUrl"
      :detailed-description="project.detailedDescription"
      :skills="project.skills"
    />
  </CategoryBlock>
</template>
