// src/components/Education/index.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia';
import { computed } from 'vue';
import { useResumeContentStore } from '@/stores/resumeContent';
import CategoryBlock from '@/components/common/CategoryBlock.vue';
import CategoryTitle from '@/components/common/CategoryTitle.vue';
import EducationSection from './EducationSection.vue';

const resumeContentStore = useResumeContentStore();
const { content } = storeToRefs(resumeContentStore);
const educationList = computed(() => content.value.education);
</script>

<template>
  <CategoryBlock>
    <CategoryTitle title="Education" />
    <dvi class="space-y-3">
      <EducationSection
        v-for="{
          school,
          degree,
          fieldOfStudy,
          startDate,
          endDate,
        } of educationList"
        :key="`${school}-${degree}-${fieldOfStudy}`"
        :school="school"
        :degree="degree"
        :fieldOfStudy="fieldOfStudy"
        :startDate="startDate"
        :endDate="endDate"
      />
    </dvi>
  </CategoryBlock>
</template>

// src/components/Education/index.svelte
<script lang="ts">
  import CategoryBlock from '$components/common/CategoryBlock.svelte';
  import CategoryTitle from '$components/common/CategoryTitle.svelte';
  import type { Education, ResumeData } from '$types/resumeData';
  import { getContext } from 'svelte';
  import type { Writable } from 'svelte/store';
  import EducationSection from './EducationSection.svelte';

  let educationList: Education[];
  const resumeData = getContext<Writable<ResumeData>>('resumeData');
  resumeData.subscribe((value) => (educationList = value.education));
</script>

<CategoryBlock>
  <CategoryTitle title={'Education'} />
  <dvi class="space-y-3">
    {#each educationList as { school, degree, fieldOfStudy, startDate, endDate }}
      <EducationSection
        {school}
        {degree}
        {fieldOfStudy}
        {startDate}
        {endDate}
      />
    {/each}
  </dvi>
</CategoryBlock>
