// src/components/Experience/ExperienceSection.svelte
<script lang="ts">
  import { decorateURL } from '$utils';
  export let title: string;
  export let companyName: string;
  export let companyUrl: string = '';
  export let location: string;
  export let startDate: Date;
  export let endDate: Date | null = null;
  export let description: string | string[] = '';
  export let skills: string[] = [];
</script>

<section>
  <div
    class="my-1 space-y-1 md:flex md:justify-between md:space-y-0 print:flex print:justify-between print:space-y-0"
  >
    <div>
      <h3 class="text-lg font-bold">
        <span class="inline-block w-5 text-left text-blue-400">
          <i class="fa-solid fa-clipboard-user" />
        </span>
        {title}
      </h3>
      <div class="font-bold">
        <span class="inline-block w-5 text-left text-slate-700">
          <i class="fa-solid fa-building" />
        </span>
        <span>
          {#if companyUrl}
            <a href={decorateURL(companyUrl)} class="underline">{companyName}</a
            >
          {:else}
            {companyName}
          {/if}
        </span>
      </div>
    </div>
    <div class="text-gray-600 md:text-right">
      <div>
        {`${startDate.toLocaleString('en-US', {
          month: 'short',
        })} ${startDate.getFullYear()}`} - {endDate
          ? `${endDate.toLocaleString('en-US', {
              month: 'short',
            })} ${endDate.getFullYear()}`
          : 'Present'}
      </div>
      <div>{location}</div>
    </div>
  </div>
  <div class="my-2">
    {#if Array.isArray(description)}
      <ul class="list-disc list-inside [hyphens:auto]">
        {#each description as descriptionItem}
          <li>{descriptionItem}</li>
        {/each}
      </ul>
    {:else if typeof description === 'string'}
      <p>{description}</p>
    {/if}
  </div>
  {#if skills?.length > 0}
    <div class="my-1">
      <span class="inline-block w-4 text-gray-600">
        <i class="fa-solid fa-screwdriver-wrench" />
      </span>
      <span class="font-medium">Skills</span>: {skills.join(', ')}
    </div>
  {/if}
</section>

// src/components/OtherExperience/ExperienceSection.vue
<script setup lang="ts">
import { decorateUrl } from '@/utils/urlUtils';
import { computed } from 'vue';
import type { ExperienceDescription } from '@/types/resumeContent';

const props = defineProps<{
  title: string;
  companyName: string;
  companyUrl?: string;
  location?: string;
  startDate: Date;
  endDate?: Date;
  description?: ExperienceDescription[];
  skills?: string[];
}>();

const startDateString = computed(
  () =>
    `${props.startDate.toLocaleString('en-US', {
      month: 'short',
    })} ${props.startDate.getFullYear()}`,
);

const endDateString = computed(() =>
  props.endDate
    ? `${props.endDate.toLocaleString('en-US', {
        month: 'short',
      })} ${props.endDate.getFullYear()}`
    : 'Present',
);
</script>

<template>
  <section class="space-y-1">
    <div class="flex justify-between text-sm text-gray-600 dark:text-gray-400">
      <div>
        {{ startDateString }}
        -
        {{ endDateString }}
      </div>
      <div v-if="location">{{ location }}</div>
    </div>
    <h3 class="text-lg font-bold">
      <div>
        <span>
          <a
            v-if="companyUrl"
            class="underline underline-offset-2"
            :href="decorateUrl(companyUrl)"
          >
            {{ companyName }}
          </a>
          <span v-else>{{ companyName }}</span>
        </span>
        <span> | </span>
        <span>{{ title }}</span>
      </div>
    </h3>
    <div>
      <ul class="list-disc list-outside pl-4 [hyphens:auto]">
        <li v-for="descriptionItem of description" :key="descriptionItem.title">
          {{ descriptionItem.title }}
          <ul
            v-if="descriptionItem.items && descriptionItem.items.length > 0"
            class="pl-4 list-circle list-outside"
          >
            <li
              v-for="descriptionItemChild of descriptionItem.items"
              :key="descriptionItemChild.title"
            >
              {{ descriptionItemChild.title }}
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div v-if="skills && skills.length > 0" class="pt-1 flex flex-wrap gap-2">
      <span
        v-for="skill of skills"
        :key="skill"
        class="text-sm whitespace-nowrap text-gray-600 dark:text-gray-400 border-2 rounded-lg border-gray-600 dark:border-gray-400 px-1"
      >
        {{ skill }}
      </span>
    </div>
  </section>
</template>
