// src/components/common/LanguageSelect.svelte
<script lang="ts">
  type Value = unknown;
  type Option = {
    key: string;
    text: string;
    value: Value;
  };
  export let options: Option[];
  export let selectedValue: Value;
  export let onValueSelect: (value: Value) => void;

  $: selectedText = options.find(({ value }) => value === selectedValue)?.text;

  let isToggle: boolean = false;
  function handleToggle() {
    isToggle = !isToggle;
  }
  function handleBlur() {
    isToggle = false;
  }
  function handleSelect(selectedValue: unknown) {
    isToggle = false;
    onValueSelect(selectedValue);
  }
</script>

<div class="relative text-gray-400 pb-2 print:hidden">
  <button
    class=" w-28 flex justify-between px-2 py-1 border border-gray-300 rounded-md"
    on:click={handleToggle}
    on:blur={handleBlur}
  >
    <span>{selectedText}</span>
    <span>
      {#if isToggle}
        <i class="fa-solid fa-angle-up" />
      {:else}
        <i class="fa-solid fa-angle-down" />
      {/if}
    </span>
  </button>
  <div
    class={`${
      isToggle ? 'block' : 'hidden'
    } absolute top-full right-0 w-full p-2 border border-gray-300 rounded-md bg-white`}
  >
    <ul class="space-y-1">
      {#each options as { key, text, value }}
        <li>
          <button
            id={key}
            class="w-full text-left whitespace-nowrap"
            on:mousedown|preventDefault
            on:click|stopPropagation={() => {
              handleSelect(value);
            }}
          >
            {text}
          </button>
        </li>
      {/each}
    </ul>
  </div>
</div>

// src/components/common/LanguageSelect.vue
<script setup lang="ts">
import { ref } from 'vue';
import { lang, LANGUAGE_OPTIONS } from '@/constant/language';
import { useLanguageStore } from '@/stores/language';
import { storeToRefs } from 'pinia';

const isToggled = ref<boolean>(false);
const languageStore = useLanguageStore();
const { language } = storeToRefs(languageStore);
const { switchLanguage } = languageStore;

function handleClick() {
  isToggled.value = true;
}
function handleBlur() {
  isToggled.value = false;
}
function handleSelect(lang: lang) {
  switchLanguage(lang);
}
</script>

<template>
  <div class="relative print:hidden">
    <button
      class="text-2xl text-gray-600"
      @click="handleClick"
      @blur="handleBlur"
    >
      <i class="fa-solid fa-language"></i>
    </button>
    <ul
      class="absolute top-full right-0 min-w-max p-2 text-gray-400 border border-gray-400 rounded-md bg-white"
      :class="{ hidden: !isToggled }"
    >
      <li v-for="{ text, value } in LANGUAGE_OPTIONS" :key="value">
        <button
          @mousedown="() => handleSelect(value)"
          :disabled="language.value === value"
        >
          {{ text }}
        </button>
      </li>
    </ul>
  </div>
</template>
